import './globals.css'

export const metadata = {
  title: 'T H X K | N E X T # 1',
  description: 'Generated by THXK-EXPENSES | POWER BY THISKOKO',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/thxkicon.ico" />
      </head>
      <body>{children}</body>
    </html>
  )
}
